### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


In [ ]:
import pandas as pd
import numpy as np

expvida = pd.read_csv("/home/leaolarte/Curso_YPF_Data_Science/DataSets/life_expectancy_data.csv")

In [2]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [3]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [4]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [5]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [6]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [7]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[9.02501495e-01 4.87304041e-01 3.28747686e-01 8.54498152e-01
 1.89294490e-02 8.07113509e-02 1.12826320e-01 8.03767230e-01
 7.13583189e-01 9.94809042e-01 9.76249869e-02 1.84517755e-01
 4.13975550e-01 6.74012445e-01 4.24424879e-01 3.71103679e-01
 1.98594409e-01 7.90977902e-01 7.39556011e-01 5.03482823e-01
 9.18267780e-01 3.05854438e-01 6.74516645e-01 4.96475129e-01
 3.30900627e-01 4.06519318e-01 7.24601647e-01 6.58277293e-02
 6.39912960e-03 5.05303780e-01 5.88749594e-01 5.69851654e-01
 8.58540960e-01 3.18121535e-01 5.75965431e-01 9.77967874e-01
 2.03015676e-01 4.68746017e-02 2.55837453e-01 9.58007597e-01
 1.76755818e-01 4.89942212e-02 6.27894126e-01 9.13510967e-01
 8.05840469e-01 4.30493481e-01 6.49034080e-01 6.68335846e-01
 4.81451124e-01 3.57130819e-01 2.20951726e-01 9.50347280e-01
 6.16041087e-01 6.89649749e-01 4.98353676e-01 6.65425420e-01
 3.80314747e-01 1.64592331e-01 5.02564730e-02 6.48087095e-01
 2.16685935e-02 1.24605926e-01 1.56428286e-01 3.80363527e-01
 2.00529053e-01 6.053720

In [10]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.49011366 0.94469854 0.53986538 0.4907626  0.10911271 0.65399728
 0.0810975  0.03864248 0.92361105 0.25202264 0.87762068 0.5378558
 0.07648063 0.59781812 0.73738682 0.94199142 0.14415293 0.87283166
 0.599447   0.13770786 0.30870908 0.4883059  0.22483254 0.26249383
 0.81513794]

Media: 0.4858678416620163

Varianza: 0.09039731399447738


In [11]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.48721488]


In [12]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)

[0.48586784]


In [13]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.08734429]


In [14]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.3194528  0.11407289 0.31930826 0.82916593 0.85259732 0.39647662
 0.47759263 0.52917728 0.74633946 0.9226131  0.73447042 0.49150907
 0.72254007 0.96153436 0.15096439]
